/* ==========================================================================
   topics.js — 留言讨论板块的话题数据（hongyuguo.com）
   每个话题对应一个产品：两个 App + 四个 VS Code 扩展。
   话题详情页与二维码均以 slug 作为唯一标识。
   ========================================================================== */
window.HY_TOPICS = [
  {
    slug: 'safevault',
    group: 'product',
    kind: 'App',
    kindZh: '应用',
    name: 'SafeVault',
    nameZh: '密码管理器',
    tagline: 'Local-first password manager for iOS / Android / macOS / Windows.',
    taglineZh: '本地优先的密码管理器，iOS / Android / macOS / Windows 四端可用。',
    icon: 'assets/products/safevault.png?v=4',
    link: 'https://safevault-service.online',
    linkLabel: '访问官网',
    linkLabelEn: 'Visit website',
  },
  {
    slug: 'maiker',
    group: 'product',
    kind: 'App',
    kindZh: '应用',
    name: 'MaiKer',
    nameZh: '壁纸应用',
    tagline: 'Wallpapers that make your Mac feel alive.',
    taglineZh: '让 Mac 桌面活起来的动态壁纸应用。',
    icon: 'assets/products/maiker.png?v=2',
    link: 'https://macwall.skin',
    linkLabel: '访问官网',
    linkLabelEn: 'Visit website',
  },
  {
    slug: 'ext-trans-picker',
    group: 'extension',
    kind: 'VS Code Extension',
    kindZh: 'VS Code 扩展',
    name: '扩展选择助手',
    nameEn: 'Extension Picker',
    en: 'ext-trans-picker',
    taglineZh: '看透外文，一目了然 — 自动把扩展详情翻译为中文，AI 总结功能、收费与使用指南。',
    taglineEn: 'Browse the VS Code Marketplace with details auto-translated to Chinese and AI summaries of features, pricing, and guides.',
    icon: 'assets/extensions/ext-trans-picker.png?v=2',
    link: 'https://marketplace.visualstudio.com/items?itemName=honor-world.ext-trans-picker',
    linkLabel: '安装扩展',
    linkLabelEn: 'Install',
  },
  {
    slug: 'dev-env-sync',
    group: 'extension',
    kind: 'VS Code Extension',
    kindZh: 'VS Code 扩展',
    name: '部署环境一键迁移',
    nameEn: 'Dev Env Sync',
    en: 'dev-env-sync',
    taglineZh: '登录 GitHub 一键拉取/上传个人开发环境：Copilot 技能、全局指令、扩展清单与工具链。',
    taglineEn: 'Sign in to GitHub and migrate your whole dev environment — Copilot skills, global instructions, extension lists, and toolchains — between devices with one click.',
    icon: 'assets/extensions/dev-env-sync.png?v=2',
    link: 'https://marketplace.visualstudio.com/items?itemName=honor-world.dev-env-sync',
    linkLabel: '安装扩展',
    linkLabelEn: 'Install',
  },
  {
    slug: 'local-skill-quick-launch',
    group: 'extension',
    kind: 'VS Code Extension',
    kindZh: 'VS Code 扩展',
    name: '本地skill快捷调用',
    nameEn: 'Local Skill Quick Launch',
    en: 'local-skill-quick-launch',
    taglineZh: '可视化勾选管理本地 Copilot 技能，自动写入全局指令，不用再记提示词。',
    taglineEn: 'Visually manage your local Copilot skills and auto-write them into your global instructions — no more memorizing prompts.',
    icon: 'assets/extensions/local-skill-quick-launch.png?v=2',
    link: 'https://marketplace.visualstudio.com/items?itemName=honor-world.local-skill-quick-launch',
    linkLabel: '安装扩展',
    linkLabelEn: 'Install',
  },
  {
    slug: 'chairmanmao-guide-life',
    group: 'extension',
    kind: 'VS Code Extension',
    kindZh: 'VS Code 扩展',
    name: '毛主席思想指导',
    nameEn: 'Mao’s Thought Guidance',
    en: 'ChairmanMao-guide-life',
    taglineZh: '以《毛泽东选集》方法论为根基的 AI 决策指导，六阶段层层分析职场与人生难题。',
    taglineEn: 'AI decision guidance grounded in the methodology of Mao’s Selected Works — six phases of pragmatic analysis for work and life.',
    icon: 'assets/extensions/chairmanmao-guide-life.png?v=2',
    link: 'https://marketplace.visualstudio.com/items?itemName=honor-world.ChairmanMao-guide-life',
    linkLabel: '安装扩展',
    linkLabelEn: 'Install',
  },
];
